bump_version: null
lint:
  files_exist:
  - conf/igenomes.config
  - conf/igenomes_ignored.config
  - assets/multiqc_config.yml
  - conf/igenomes.config
  - conf/igenomes_ignored.config
  - assets/multiqc_config.yml
  files_unchanged:
  - .github/CONTRIBUTING.md
  - assets/sendmail_template.txt
  - .github/CONTRIBUTING.md
  - assets/sendmail_template.txt
  multiqc_config: false
nf_core_version: 3.0.2
org_path: null
repository_type: pipeline
template:
  author: Antoine Buetti-Dinh
  description: just basic template to build upon more stuff
  force: true
  is_nfcore: true
  name: basictemplate
  org: nf-core
  outdir: .
  skip_features:
  - igenomes
  - multiqc
  - fastqc
  version: 1.0.0dev
update: null
