contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here
  - name: "Slack #basictemplate channel"
    url: https://nfcore.slack.com/channels/basictemplate
    about: Discussion about the nf-core/basictemplate pipeline
